config/routes.rb
  get 'member-api/v2/files/restore/:generic_file_identifier', to: 'generic_files#restore', format: :json, generic_file_identifier: file_ptrn
  put 'api/v2/files/restore/:generic_file_identifier', to: 'generic_files#restore', format: :json, generic_file_identifier: file_ptrn


  # INSTITUTIONS (API)
  # resources :institutions doesn't like this route for #show, because it interprets .edu/.org/.com as an 'unknown format'
  get 'api/v2/institutions/:institution_identifier', to: 'institutions#show', format: [:json], institution_identifier: institution_ptrn

  # PREMIS EVENT ROUTES
  uuid_pattern = /([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}){1}/
  get '/api/v2/events/:identifier', to: 'premis_events#show', format: [:json], identifier: uuid_pattern
  get 'events/:file_identifier', to: 'premis_events#index', format: [:json, :html], file_identifier: file_ptrn, as: :generic_file_events
  get 'events/:object_identifier', to: 'premis_events#index', format: [:json, :html], object_identifier: object_ptrn, as: :intellectual_object_events
  get 'events/:institution_identifier', to: 'premis_events#index', format: [:json, :html], institution_identifier: institution_ptrn, as: :institution_events
  get 'events/:id', to: 'premis_events#show', format: [:json, :html], as: :premis_event
  get '/api/v2/events', to: 'premis_events#index', format: [:json, :html]
  post '/api/v2/events', to: 'premis_events#create', format: :json
  get '/api/v2/events/:id', to: 'premis_events#show', format: [:json, :html]
  get 'member-api/v2/events/:file_identifier', to: 'premis_events#index', format: :json, file_identifier: file_ptrn
  get 'member-api/v2/events/:object_identifier', to: 'premis_events#index', format: :json, object_identifier: object_ptrn
  get 'member-api/v2/events/:institution_identifier', to: 'premis_events#index', format: :json, institution_identifier: institution_ptrn
  get 'notifications/failed_fixity', to: 'premis_events#notify_of_failed_fixity', format: :json
  get '/api/v2/notifications/failed_fixity', to: 'premis_events#notify_of_failed_fixity', format: :json

  # WORK ITEM ROUTES
  resources :work_items, only: [:index, :create, :show, :update, :edit], format: [:html, :json], path: 'items'
  put 'items/', to: 'work_items#update', format: :json
  resources :work_items, path: '/api/v2/items'
  resources :work_items, only: [:index], path: 'member-api/v2/items', format: [:json, :html]
  get '/api/v2/items/:etag/:name/:bag_date', to: 'work_items#show', as: :work_item_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  put '/api/v2/items/:etag/:name/:bag_date', to: 'work_items#update', format: 'json', as: :work_item_api_update_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  get 'items/items_for_restore', to: 'work_items#items_for_restore', format: :json
  get 'items/items_for_delete', to: 'work_items#items_for_delete', format: :json
  get 'items/ingested_since', to: 'work_items#ingested_since', format: :json
  get 'items/set_restoration_status', to: 'work_items#set_restoration_status', format: :json
  get 'api/v2/items/search', to: 'work_items#api_search', format: :json
  get 'items/:id/requeue', to: 'work_items#requeue', format: [:json, :html], as: :requeue_work_item
  get 'notifications/successful_restoration', to: 'work_items#notify_of_successful_restoration', format: :json
  get '/api/v2/notifications/successful_restoration', to: 'work_items#notify_of_successful_restoration', format: :json
  get 'notifications/spot_test_restoration/:id', to: 'work_items#spot_test_restoration', format: :json
  get '/api/v2/notifications/spot_test_restoration/:id', to: 'work_items#spot_test_restoration', format: :json

  # WORK ITEM STATE ROUTES
  #resources :work_item_states, path: 'item_state', only: [:show, :update, :create], format: :json, param: :work_item_id
  #resources :work_item_states, path: '/api/v2/item_state', only: [:show, :update, :create], format: :json, param: :work_item_id
  post '/api/v2/item_state', to: 'work_item_states#create', format: :json
  put '/api/v2/item_state/:id', to: 'work_item_states#update', format: :json
  get '/api/v2/item_state/:id', to: 'work_item_states#show', format: :json

  # CHECKSUM ROUTES
  get '/api/v2/checksums', to: 'checksums#index', format: :json
  get '/api/v2/checksums/:id', to: 'checksums#show', format: :json
  post '/api/v2/checksums/:generic_file_identifier', to: 'checksums#create', format: :json, generic_file_identifier: /.*/

  # CATALOG ROUTES
  post 'search/', to: 'catalog#search', format: [:json, :html], as: :search
  get 'search/', to: 'catalog#search', format: [:json, :html]
  get 'api/v2/search', to: 'catalog#search', format: [:json, :html], as: :api_search
  get 'feed', to: 'catalog#feed', format: :rss, as: :rss_feed

  # REPORT ROUTES
  get 'reports/:identifier', to: 'reports#index', format: [:json, :html], as: :reports, identifier: institution_ptrn
  get 'reports/overview/:identifier', to: 'reports#overview', format: [:json, :html, :pdf], as: :institution_overview, identifier: institution_ptrn
  get 'reports/general/:identifier', to: 'reports#general', format: [:json, :html, :pdf], as: :institution_general_report, identifier: institution_ptrn
  get 'reports/cost/:identifier', to: 'reports#cost', format: [:json, :html, :pdf], as: :institution_cost_report, identifier: institution_ptrn
  get 'reports/subscribers/:identifier', to: 'reports#subscribers', format: [:json, :html, :pdf], as: :institution_subscribers_report, identifier: institution_ptrn
  get 'reports/timeline/:identifier', to: 'reports#timeline', format: [:json, :html, :pdf], as: :institution_timeline_report, identifier: institution_ptrn
  get 'reports/mimetype/:identifier', to: 'reports#mimetype', format: [:json, :html, :pdf], as: :institution_mimetype_report, identifier: institution_ptrn
  get 'reports/institution_breakdown', to: 'reports#institution_breakdown', format: [:json, :html, :pdf], as: :institution_breakdown
  get 'reports/object_report/:intellectual_object_identifier', to: 'reports#object_report', format: [:json, :html], as: :object_report, intellectual_object_identifier: object_ptrn

  # ALERT ROUTES
  get 'alerts/', to: 'alerts#index', format: [:json, :html], as: :alerts
  get 'alerts/summary', to: 'alerts#summary', format: [:json, :html], as: :alerts_summary

  # EMAIL ROUTES
  resources :emails, path: 'email_logs', only: [:index, :show], format: [:json]

  # SNAPSHOT ROUTES
  resources :snapshots, path: 'snapshots', only: [:index, :show], format: [:json, :html]

  # BULK DELETE JOB ROUTES
  resources :bulk_delete_jobs, path: 'bulk_delete_jobs', only: [:index, :show], format: [:json, :html]
  resources :bulk_delete_jobs, path: 'api/v2/bulk_delete_jobs', only: [:index, :show], format: :json

  # USER ROUTES
  devise_for :users,
  pathnames: {
      verify_authy: '/verify-token',
      enable_authy: '/enable-authy',
      verify_authy_installation: '/verify-installation'
  }

  resources :users do
    patch 'update_password', on: :collection
    get 'edit_password', on: :member
    patch 'generate_api_key', on: :member
  end
  get 'users/:id/admin_password_reset', to: 'users#admin_password_reset', as: :admin_password_reset_user
  get 'users/:id/forced_password_update', to: 'users#forced_password_update', as: :user_forced_password_update
  get 'users/:id/deactivate', to: 'users#deactivate', as: :deactivate_user
  get 'users/:id/reactivate', to: 'users#reactivate', as: :reactivate_user
  get '/vacuum', to: 'users#vacuum', format: [:json, :html], as: :vacuum
  get '/api/v2/vacuum', to: 'users#vacuum', format: [:json, :html], as: :api_vacuum
  get '/notifications/stale_users', to: 'users#stale_user_notification', format: [:json, :html], as: :stale_users
  get '/api/v2/notifications/stale_users', to: 'users#stale_user_notification', format: [:json, :html], as: :api_stale_users
  get '/account_confirmations', to: 'users#account_confirmations', format: [:json, :html], as: :account_confirmations
  get '/api/v2/account_confirmations', to: 'users#account_confirmations', format: [:json, :html], as: :api_account_confirmations
  get '/users/:id/individual_account_confirmation', to: 'users#indiv_confirmation_email', format: [:json, :html], as: :indiv_confirmation_email
  get '/api/v2/users/:id/individual_account_confirmation', to: 'users#indiv_confirmation_email', format: [:json, :html], as: :api_indiv_confirmation_email
  get '/users/:id/confirm_account', to: 'users#confirm_account', format: [:json, :html], as: :confirm_account
  get '/api/v2/users/:id/confirm_account', to: 'users#confirm_account', format: [:json, :html], as: :api_confirm_account
  get 'users/:id/enable_otp', to: 'users#enable_otp', as: :users_enable_otp
  get 'users/:id/disable_otp', to: 'users#disable_otp', as: :users_disable_otp
  get 'users/:id/register_authy', to: 'users#register_authy_user', as: :users_register_for_authy
  get 'users/:id/change_authy_phone_number', to: 'users#change_authy_phone_number', as: :user_authy_number
  get 'users/:id/verify_twofa', to: 'users#verify_twofa', as: :users_verify_twofa
  get 'users/:id/backup_codes', to: 'users#generate_backup_codes', as: :backup_codes
  get 'users/:id/two_factor_text_link', to: 'users#two_factor_text_link', as: :twofa_text
  get 'users/:id/verify_email', to: 'users#verify_email', as: :email_verification
  get 'users/:id/email_confirmation', to: 'users#email_confirmation', as: :email_confirmation

  resources :verifications, only: [:edit, :update]
  get 'verifications/login', to: 'verifications#login', as: :verification_login
  get 'verifications/enter_backup/:id', to: 'verifications#enter_backup', as: :enter_backup_verification
  put 'verifications/check_backup/:id', to: 'verifications#check_backup', as: :check_backup_verification

  #get '/verification_callback', to: 'application#callback', as: :verification_callback

  authenticated :user do
    root to: 'institutions#show', as: 'authenticated_root'
  end

  root :to => 'institutions#show'

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  self.primary_key = 'id'
  belongs_to :institution, foreign_key: :institution_id
  has_and_belongs_to_many :roles

  # Include default devise modules. Others available are:
  # :database_authenticatable,
  # :recoverable, :rememberable, :trackable, :validatable,
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :recoverable, :rememberable, :trackable, :password_archivable,
         :timeoutable, :validatable, :two_factor_authenticatable,
         :two_factor_backupable, otp_backup_code_length: 10, :otp_secret_encryption_key => ENV['TWO_FACTOR_KEY']

  validates :email, presence: true, uniqueness: true
  validate :email_is_valid
  # validates :phone_number, presence: true
  validates_presence_of :phone_number, on: :enable_otp
  validates :role_ids, presence: true
  validates :institution_id, presence: true
  validate :institution_id_points_at_institution
  validates :name, presence: true
  phony_normalize :phone_number, :default_country_code => 'US'
  validates_plausible_phone :phone_number
  validate :init_grace_period, on: :create

  # We want this to always be true so that authorization happens in the user policy, preventing incorrect 404 errors.
  scope :readable, ->(current_user) { where('(1=1)') }

  # This method assigns permission groups
  # Don't think these are necessary anymore, we use Pundit/Roles
  def groups
    institution_groups + ['registered']
  end

  def institution_groups
    if institutional_admin?
      ["Admin_At_#{institution_group_suffix}", 'institutional_admin']
    elsif institutional_user?
      ["User_At_#{institution_group_suffix}", 'institutional_user']
    else
      ['admin']
    end
  end

  def institution_group_suffix
    institution_id
  end

  def to_s
    name || email
  end

  def as_json(options = nil)
    json_data = super
    json_data.delete('api_secret_key')
    json_data.delete('encrypted_api_secret_key')
    json_data
  end

  def is?(role)
    self.roles.pluck(:name).include?(role.to_s)
  end

  def admin?
    is? 'admin'
  end

  def institutional_admin?
    is? 'institutional_admin'
  end

  def institutional_user?
    is? 'institutional_user'
  end

  def sms_user?
    self.authy_status == 'sms' || self.authy_status.nil?
  end

  def need_two_factor_authentication?
    self.enabled_two_factor == true && self.confirmed_two_factor == true
  end

  def required_to_use_twofa?
    self.institution.otp_enabled || self.admin? || self.institutional_admin?
  end

  def self.stale_users
    users = User.where('created_at <= ? AND created_at >= ?',
                       DateTime.now - (ENV['PHAROS_2FA_GRACE_PERIOD'].to_i - 3).days,
                       DateTime.now - (ENV['PHAROS_2FA_GRACE_PERIOD'].to_i + 7).days, )
    stale_users = []
    users.each do |usr|
      items = WorkItem.where(user: usr.email)
      stale_users.push(usr) if items.count == 0
    end
    stale_users
  end

  def role_id
    if(admin?)
      Role.where(name: 'admin').first_or_create.id
    elsif(institutional_admin?)
      Role.where(name: 'institutional_admin').first_or_create.id
    elsif(institutional_user?)
      Role.where(name: 'institutional_user').first_or_create.id
    end
  end

  def guest?
    false
  end

  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deactivated_at, Time.current)
    update_attribute(:encrypted_api_secret_key, '')
  end

  def reactivate
    update_attribute(:deactivated_at, nil)
  end

  def deactivated?
    return !self.deactivated_at.nil?
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deactivated_at
  end

  # provide a custom message for a deleted account
  def inactive_message
    !deactivated_at ? super : :deactivated_account
  end

  attr_reader :api_secret_key

  def api_secret_key=(key)
    @api_secret_key = key
    self.encrypted_api_secret_key = if key.blank?
                                      nil
                                    else
                                      password_digest(key)
                                    end
  end

  # Generate a new API key for this user
  def generate_api_key(length = 20)
    self.api_secret_key = SecureRandom.hex(length)
  end

  # Verifies whether an API key (from sign in) matches the user's API key.
  def valid_api_key?(input_key)
    return false if encrypted_api_secret_key.blank?
    bcrypt  = ::BCrypt::Password.new(encrypted_api_secret_key)
    key = ::BCrypt::Engine.hash_secret("#{input_key}#{User.pepper}", bcrypt.salt)
    Devise.secure_compare(key, encrypted_api_secret_key)
  end

  # Sets a custom session time (in seconds) for the current user.
  def set_session_timeout(seconds)
    @session_timeout = seconds
  end

  # Returns the session duration, in seconds, for the current user.
  # For API use sessions, we set a long timeout
  # For all other users, we use the config setting Devise.timeout_in,
  # which is set in config/initializers/devise.rb.
  # For info on the timeout_in method, see:
  # https://github.com/plataformatec/devise/wiki/How-To:-Add-timeout_in-value-dynamically
  def timeout_in
    if !@session_timeout.nil? && @session_timeout > 0
      @session_timeout
    else
      Devise.timeout_in
    end
  end

  private

  def institution_id_points_at_institution
    errors.add(:institution_id, 'is not a valid institution') unless Institution.exists?(institution_id)
  end

  def email_is_valid
    errors.add(:email, 'is invalid') if !EmailValidator.valid?(email)
  end

  def phone_number_length
    errors.add(:phone_number, 'is not the proper length') if phone_number.length < 10
  end

  def init_grace_period
    self.grace_period = DateTime.now
  end

  def self.phone_number_is_valid

  end

end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  # Returns a list of roles we have permission to assign
  def roles_for_select
    Role.all.select {|role| policy(role).add_user? }.sort.map {|r| [r.name.titleize, r.id] }
  end

  def institutions_for_select
    Institution.all.order('name').select {|institution| policy(institution).add_user? }
  end

  def generate_key_confirmation_msg(user)
    if user.encrypted_api_secret_key
      'Are you sure?  Your current API secret key will be destroyed and replaced with the new one.'
    else
      ''
    end
  end

  def persist_errors(user)
    user.errors.add(:phone_number, @user.errors.messages[:phone_number][0]) if @user && @user.errors.any? && user.id == @user.id
    user
  end
end

app/views/users/_api_key.html.erb
<% if policy(@user).generate_api_key? %>
    <h4> API Secret Key </h4>

    <% unless @user.encrypted_api_secret_key.nil? || @user.encrypted_api_secret_key == '' %>
        <% if @user == current_user %>
            <div>You already have an API key. If you've forgotten it, you'll need to generate a new one.</div>
            <br>
        <% else %>
            <div>This user already has an API Secret Key.</div>
            <br>
        <% end %>
    <% else %>
        <div> You do not have an API secret key yet. </div>
        <br />
    <% end %>

    <div>
      <%= link_to 'Generate API Secret Key',
                  generate_api_key_user_path(@user),
                  class: 'btn doc-action-btn btn-normal',
                  method: :patch,
                  data: { confirm: generate_key_confirmation_msg(@user) } %>
    </div>
    <br />

    <div>
      You should treat your API secret key the same way you would treat a password:
      <ul>
        <li> Don't share it with other people </li>
        <li> Don't send it over email or other insecure communications </li>
        <li> Use proper file protections (e.g. chmod) so that other people cannot read it from your configuration files or scripts </li>
      </ul>
    </div>

<% end %>

app/views/users/confirm_two_factor.html.erb
<h2>Please finish the verification process by entering the code that was sent to you via SMS.</h2>

<%= form_tag(confirm_two_factor_update_path, :method => :put) do %>
    <%= devise_error_messages! %>

    <%= text_field_tag :code %>
    <%= submit_tag 'Verify Mobile Phone Number' %>
<% end %>

app/views/users/show.html.erb
<% @title = "#{@user.name}'s Account" %>

<h4>User Information</h4>
<%= gravatar_for @user %>
<address>
  <strong><%= @user.name %></strong> (<em><%= @user.institution.name %></em>)<br />
  Email: <a href="mailto:#"><%= @user.email %></a><br />
  Mobile Phone Number: <%= @user.phone_number %> <br /><br />
</address>
<%= edit_link(@user) %>
<%= link_to 'Change Password', edit_password_user_path(@user), class: 'btn btn-normal doc-action-btn btn-sm' %>

<% if current_user.admin? || current_user.institutional_admin? %>
    <%= link_to 'Force Password Update', user_forced_password_update_path(@user), class: 'btn btn-warning doc-action-btn btn-sm' %>
<% end %>
<% if @user.deactivated? %>
    <%= reactivate_link(@user) %>
<% else %>
    <%= deactivate_link(@user) %>
<% end %>
<%= destroy_link(@user) %>
<br><br>
<% unless @user.email_verified %>
    <h5>Resend Email Verification</h5>
    <p>If you lost, or never received, a welcome email and have not changed your password you may need to verify your email. Please do so now. </p>
    <%= button_to 'Send Email Verification Instructions', email_verification_path(@user.id),
                  :method => :get, class: 'btn btn-normal doc-action-btn' %>
<% end %>

<% unless @user.account_confirmed %>
    <h5>Resend Account Confirmation Email</h5>
    <p>If you lost, or never received, an email with a confirmation URL for your account confirmation you can resend a confirmation email here. </p>
    <%= link_to 'Resend Email', indiv_confirmation_email_path(@user), class: 'btn btn-normal doc-action-btn btn-sm' %>
<% end %>

<hr />

<h4>Two Factor Authentication (2FA)</h4>
<% if @user.enabled_two_factor %>
    <% if @user.confirmed_two_factor %>
		<h5>Status: Enabled</h5>
        <%= link_to 'Disable 2FA', users_disable_otp_path(@user.id), id: 'disable_twofa',
                    :method => :get, class: 'btn btn-warning doc-action-btn' %>
        <% if (current_user.authy_id.nil? || current_user.authy_id == '') %>
            <%= link_to 'Register w/Authy', users_register_for_authy_path(@user.id), id: 'register_with_authy',
                        :method => :get, class: 'btn btn-primary doc-action-btn' %>
        <% end %>
		<%= link_to 'Change Mobile Phone Number', "#", class: 'btn btn-normal doc-action-btn btn-sm', data: {toggle: "modal", target: "#authy_phone_modal"} %>
		<%= render 'authy_phone_number_modal' %>
		<% if @user.errors.any? %>
		   <script>$('#authy_phone_modal').modal('show');</script>
		<% end %>
    <% else %>
        <h5>Status: Mobile Phone Number Needs Verification</h5>
        <p>If the phone number in your user profile is not able to receive text messages or push notifications you will need your
          institutional administrator or an APTrust administrator to change the number to one capable of receiving text messages.
          After that has been done, you can continue with the phone number verification process. </p>
        <%= link_to 'Verify Phone Number via SMS', users_verify_twofa_path(@user.id, verification_option: 'sms'),
                    class: 'btn btn-normal doc-action-btn' %>
        <br />
        <%= link_to 'Verify Phone Number via Push Notification', users_verify_twofa_path(@user.id, verification_option: 'push'),
                    class: 'btn btn-normal doc-action-btn', id: 'phone_verification_push_btn' %><p>(requires Authy app installation)</p>
        <%= link_to 'Disable 2FA', users_disable_otp_path(@user.id), id: 'disable_twofa',
        :method => :get, class: 'btn btn-warning doc-action-btn' %>
        <div id="verification-loader" class="hidden">
          <h4>Please check your Authy app for a push notification. Waiting for a response...</h4>
          <div class="loader"></div>
        </div>
    <% end %>

    <br />
    <br />
    <h4>Backup Codes</h4>
    <%= button_to 'Generate Backup Codes', backup_codes_path(@user.id),
                  :method => :get, class: 'btn btn-normal doc-action-btn' %>
    <% if @codes %>
        <br />
        <p><span class="badge badge-danger">Important!</span> Write these backup codes down in a safe place.
          Each code can be used once to login to your account in case your two factor device is unavailable.
          For security reasons they will not be displayed again.</p>
        <ul class='unstyled'>
          <% @codes.each do |code| %>
              <li><%= code %></li>
          <% end %>
        </ul>
    <% end %>
    <br />

<% else %>
    <h5>Status: Not Enabled</h5>
    <p>Please ensure you have an accurate phone number listed in your profile before you enable two factor authentication. </p>
    <%= link_to 'Enable 2FA', "#", class: 'btn btn-success doc-action-btn', data: {toggle: "modal", target: "#enable_phone_modal"} %>
    <%= render 'enable_phone_number_modal' %>
    <% if @user.errors.any? %>
        <script>$('#enable_phone_modal').modal('show');</script>
    <% end %>
<% end %>

<div>
  <h5>If you haven't already, consider downloading Authy and using push notifications!</h5>
  <span><a href="https://play.google.com/store/apps/details?id=com.authy.authy" target="_blank">
      <%= image_tag("aptrust/google-play.svg", size: "152x40", alt: "Get it on Google Play") %>
    </a>
  </span>
  <span><a href="https://itunes.apple.com/us/app/authy/id494168017" target="_blank">
      <%= image_tag("aptrust/app-store.svg", size: "152x40", alt: "Download on the App Store") %>
    </a>
  </span>
</div>

<hr />

<h4>Roles</h4>
<ul class="unstyled">
  <% @user.roles.each do |role| %>
      <li><%= role.name.titleize %></li>
  <% end %>
</ul>

<hr />

<%= render 'api_key' %>

<hr />

<h4>AWS Buckets</h4>
<ul clas="unstyled">
  <li><strong>Receiving Bucket: </strong><%= @user.institution.receiving_bucket %></li>
  <li><strong>Restore Bucket: </strong><%= @user.institution.restore_bucket %></li>
</ul>

app/views/users/vacuum.html.erb
<% @title = 'Vacuum Functions' %>

<table>
  <tr>
    <td><ul>
      <li><%= link_to vacuum_path(vacuum_target: 'entire_database'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Entire Database
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'checksums'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Checksum Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'confirmation_tokens'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Confirmation Token Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'emails'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Email Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'generic_files'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Generic File Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'institutions'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Institution Table
        <% end %></li><br>
    </ul></td>
    <td><ul>
      <li><%= link_to vacuum_path(vacuum_target: 'intellectual_objects'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Intellectual Object Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'premis_events'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Premis Event Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'roles'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Role Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'snapshots'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Snapshot Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'usages_samples'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Usage Sample Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'users'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum User Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'work_items'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Work Item Table
        <% end %></li><br>
      <li><%= link_to vacuum_path(vacuum_target: 'work_item_states'), {class: 'btn doc-action-btn btn-normal'} do %>
            <i class="glyphicon glyphicon-hourglass"></i> Vacuum Work Item State Table
        <% end %></li><br>
    </ul></td>
  </tr>
</table>