config/routes.rb
Rails.application.routes.draw do

  # INSTITUTION ROUTES
  institution_ptrn = /(?:[a-zA-Z0-9\-_]+)(?:\.[a-zA-Z]+)+/
  resources :institutions, format: [:json, :html], param: :institution_identifier, institution_identifier: institution_ptrn
  resources :institutions, only: [:index], format: :json, param: :institution_identifier, institution_identifier: institution_ptrn, path: 'api/v2/institutions'
  get ':institution_identifier/single_snapshot', to: 'institutions#single_snapshot', format: [:html, :json], institution_identifier: institution_ptrn, as: :institution_snapshot
  get 'api/v2/:institution_identifier/single_snapshot', to: 'institutions#single_snapshot', format: [:html, :json], institution_identifier: institution_ptrn, as: :api_institution_snapshot
  get '/group_snapshot', to: 'institutions#group_snapshot', format: [:html, :json], as: :group_snapshot
  get 'api/v2/group_snapshot', to: 'institutions#group_snapshot', format: [:html, :json], as: :api_group_snapshot
  get '/:institution_identifier/deactivate', to: 'institutions#deactivate', as: :deactivate_institution, institution_identifier: institution_ptrn
  get '/:institution_identifier/reactivate', to: 'institutions#reactivate', as: :reactivate_institution, institution_identifier: institution_ptrn
  get '/:institution_identifier/enable_otp', to: 'institutions#enable_otp', as: :enable_otp_institution, format: [:html, :json], institution_identifier: institution_ptrn
  get '/:institution_identifier/disable_otp', to: 'institutions#disable_otp', as: :disable_otp_institution, format: [:html, :json], institution_identifier: institution_ptrn
  post 'api/v2/:institution_identifier/trigger_bulk_delete', to: 'institutions#trigger_bulk_delete', as: :api_bulk_deletion, format: :json, institution_identifier: institution_ptrn
  get '/:institution_identifier/confirm_bulk_delete_institution', to: 'institutions#partial_confirmation_bulk_delete', as: :bulk_deletion_institutional_confirmation, format: [:html, :json], institution_identifier: institution_ptrn
  post 'api/v2/:institution_identifier/confirm_bulk_delete_institution', to: 'institutions#partial_confirmation_bulk_delete', as: :api_bulk_deletion_institutional_confirmation, format: :json, institution_identifier: institution_ptrn
  get '/:institution_identifier/confirm_bulk_delete_admin', to: 'institutions#final_confirmation_bulk_delete', as: :bulk_deletion_admin_confirmation, format: [:html, :json], institution_identifier: institution_ptrn
  post 'api/v2/:institution_identifier/confirm_bulk_delete_admin', to: 'institutions#final_confirmation_bulk_delete', as: :api_bulk_deletion_admin_confirmation, format: :json, institution_identifier: institution_ptrn
  get '/:institution_identifier/finished_bulk_delete', to: 'institutions#finished_bulk_delete', as: :bulk_deletion_finished, format: [:html, :json], institution_identifier: institution_ptrn
  post 'api/v2/:institution_identifier/finished_bulk_delete', to: 'institutions#finished_bulk_delete', as: :api_bulk_deletion_finished, format: :json, institution_identifier: institution_ptrn
  get '/notifications/deletion', to: 'institutions#deletion_notifications', as: :institution_deletion_notifications, format: [:html, :json]
  get 'api/v2/notifications/deletion', to: 'institutions#deletion_notifications', as: :api_institution_deletion_notifications, format: [:html, :json]
  get '/:institution_identifier/mass_forced_password_update', to: 'institutions#mass_forced_password_update', as: :mass_forced_password_update, format: [:html, :json], institution_identifier: institution_ptrn
  get 'api/v2/:institution_identifier/mass_forced_password_update', to: 'institutions#mass_forced_password_update', as: :api_mass_forced_password_update, format: [:html, :json], institution_identifier: institution_ptrn

  # Admin URL for monthly deposit report
  get 'api/v2/deposit_summary', to: 'institutions#deposit_summary', as: :institution_deposit_summary, format: [:json]


  # INTELLECTUAL OBJECT ROUTES
  object_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org|\.museum)(\%|\/)[\w\-\.\%\?\=\(\)\:\#\[\]\!\$\&\'\*\+\,\;\_\~\ \p{L}]+/
  resources :intellectual_objects, only: [:show, :edit, :update, :destroy], format: [:json, :html], param: :intellectual_object_identifier, intellectual_object_identifier: object_ptrn, path: 'objects'
  get 'objects/:intellectual_object_identifier/restore', to: 'intellectual_objects#restore', format: [:json, :html], intellectual_object_identifier: object_ptrn, as: :intellectual_object_restore
  get 'objects', to: 'intellectual_objects#index', format: [:json, :html]
  get 'objects/:institution_identifier', to: 'intellectual_objects#index', format: [:json, :html], institution_identifier: institution_ptrn, as: :intellectual_objects
  resources :intellectual_objects, only: [:show, :update, :destroy], format: :json, param: :intellectual_object_identifier, intellectual_object_identifier: object_ptrn, path: 'api/v2/objects'
  get 'api/v2/objects/:institution_identifier', to: 'intellectual_objects#index', format: [:json, :html], institution_identifier: institution_ptrn
  get 'api/v2/objects', to: 'intellectual_objects#index', format: [:json, :html]
  post 'api/v2/objects/:institution_identifier', to: 'intellectual_objects#create', format: :json, institution_identifier: institution_ptrn
  get 'member-api/v2/objects/:institution_identifier', to: 'intellectual_objects#index', format: [:json, :html], institution_identifier: institution_ptrn
  get 'member-api/v2/objects/', to: 'intellectual_objects#index', format: [:json, :html]
  get 'member-api/v2/objects/:intellectual_object_identifier/restore', to: 'intellectual_objects#restore', format: :json, intellectual_object_identifier: object_ptrn
  put 'api/v2/objects/:intellectual_object_identifier/restore', to: 'intellectual_objects#restore', format: :json, intellectual_object_identifier: object_ptrn
  delete 'api/v2/objects/:intellectual_object_identifier/delete', to: 'intellectual_objects#destroy', format: :json, intellectual_object_identifier: object_ptrn
  delete 'objects/:intellectual_object_identifier/confirm_delete', to: 'intellectual_objects#confirm_destroy', format: [:html, :json], intellectual_object_identifier: object_ptrn, as: :object_confirm_destroy
  delete 'api/v2/objects/:intellectual_object_identifier/confirm_delete', to: 'intellectual_objects#confirm_destroy', format: :json, intellectual_object_identifier: object_ptrn, as: :api_object_confirm_destroy
  get 'objects/:intellectual_object_identifier/confirm_delete', to: 'intellectual_objects#confirm_destroy', format: [:html, :json], intellectual_object_identifier: object_ptrn, as: :get_object_confirm_destroy
  get 'api/v2/objects/:intellectual_object_identifier/confirm_delete', to: 'intellectual_objects#confirm_destroy', format: :json, intellectual_object_identifier: object_ptrn, as: :get_api_object_confirm_destroy
  get 'objects/:intellectual_object_identifier/finish_delete', to: 'intellectual_objects#finished_destroy', format: [:html, :json], intellectual_object_identifier: object_ptrn, as: :get_object_finish_destroy
  get 'api/v2/objects/:intellectual_object_identifier/finish_delete', to: 'intellectual_objects#finished_destroy', format: :json, intellectual_object_identifier: object_ptrn, as: :get_api_object_finish_destroy

  # GENERIC FILE ROUTES
  file_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org|\.museum)(\%2[Ff]|\/)+[\w\-\/\.\%\?\=\(\)\:\#\[\]\!\$\&\'\*\+\,\;\_\~\ \p{L}]+(\%2[fF]|\/)+[\w\-\/\.\%\@\?\=\(\)\:\#\[\]\!\$\&\'\*\+\,\;\_\~\ \p{L}]+/
  resources :generic_files, only: [:show, :update, :destroy], format: [:json, :html], defaults: { format: :html }, param: :generic_file_identifier, generic_file_identifier: file_ptrn, path: 'files'
  resources :generic_files, only: [:show, :update, :destroy], format: [:json, :html], defaults: { format: :json }, param: :generic_file_identifier, generic_file_identifier: file_ptrn, path: 'api/v2/files'
  get '/api/v2/files/:institution_identifier', to: 'generic_files#index', format: [:json, :html], institution_identifier: institution_ptrn, as: :institution_files_api
  get '/api/v2/files/:intellectual_object_identifier', to: 'generic_files#index', format: [:json, :html], intellectual_object_identifier: object_ptrn, as: :intellectual_object_files_api
  get '/api/v2/files/', to: 'generic_files#index', format: [:json], as: :generic_files_admin_list
  get 'files/:institution_identifier', to: 'generic_files#index', format: [:json, :html], institution_identifier: institution_ptrn, as: :institution_files
  get 'files/:intellectual_object_identifier', to: 'generic_files#index', format: [:json, :html], intellectual_object_identifier: object_ptrn, as: :intellectual_object_files
  post '/api/v2/files/:intellectual_object_id/create_batch', to: 'generic_files#create_batch', format: :json
  post '/api/v2/files/:intellectual_object_identifier', to: 'generic_files#create', format: :json, intellectual_object_identifier: object_ptrn
  put '/api/v2/files/:intellectual_object_identifier', to: 'generic_files#update', format: :json, intellectual_object_identifier: object_ptrn
  resources :generic_files, only: [:index, :create], format: [:json, :html], param: :intellectual_object_identifier, intellectual_object_identifier: object_ptrn, path: 'api/v2/files'
  get 'member-api/v2/files/:intellectual_object_identifier', to: 'generic_files#index', format: :json, intellectual_object_identifier: object_ptrn
  get 'member-api/v2/files/:institution_identifier', to: 'generic_files#index', format: :json, institution_identifier: institution_ptrn
  delete 'files/confirm_delete/:generic_file_identifier', to: 'generic_files#confirm_destroy', format: [:html, :json], generic_file_identifier: file_ptrn, as: :file_confirm_destroy
  delete 'api/v2/files/confirm_delete/:generic_file_identifier', to: 'generic_files#confirm_destroy', format: [:html, :json], generic_file_identifier: file_ptrn, as: :api_file_confirm_destroy

app/views/shared/404.html.erb
<h2 class="fourohfour">404</h2>
<h3>Zoinks!</h3>

<p>The page you were looking for could not be found! If you were searching for a specific object or file, check to make sure you
have the correct identifier and try again. If you believe you have reached this message in error, please contact your administrator
or an APTrust administrator.</p>

<a class="btn doc-action-btn btn-primary" href="#" onclick="history.go(-1)" >Go Back</a>

app/views/shared/_compact_pagination.html.erb
<div class="col-md-9">
  <div class="pagination">
    <%= paginate @paged_results, @count, :window => 2 %>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<div id="main-flashes">
  <div class="flash_messages">
    <% if flash[:alert] %>
        <div class="alert alert-warning">
            <%= flash[:alert] %>
            <a class="close" data-dismiss="alert" href="#">×</a>
        </div>
    <% end %>
    <% if flash[:notice] %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
          <a class="close" data-dismiss="alert" href="#">×</a>
        </div>
    <% end %>
    <% if flash[:success] %>
        <div class="alert alert-success">
          <%= flash[:success] %>
          <a class="close" data-dismiss="alert" href="#">×</a>
        </div>
    <% end %>
    <% if flash[:error] %>
        <div class="alert alert-danger">
          <%= flash[:error] %>
          <a class="close" data-dismiss="alert" href="#">×</a>
        </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
     <p>&copy; 2013 - <%= Date.today.year %> Academic Preservation Trust
        <em><%= display_version %></em></p>
    <nav>
      <ul>
        <li><%= link_to "About", "http://aptrust.org/about", {target: "_blank"} %></li>
        <li><%= link_to "Contact", "http://aptrust.org/contact", {target: "_blank"} %></li>
        <li><%= mail_to "help@aptrust.org", "help@aptrust.org",  subject: "Admin Interface Help Request" %></li>
      </ul>
    </nav>
  </div>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-82078949-2', 'auto');
        ga('send', 'pageview');
    </script>
</footer>

app/views/shared/_header_navbar.html.erb
<div id="header-navbar" class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">

    <div id ="logo-area" class="navbar-header col-md-3">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#user-util-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to image_tag("aptrust/logoWhite.png", height: 60, width: 325, border: 0, alt: "APTrust Logo"), root_path, class: "navbar-brand logo-text" %>
    </div>

    <div class="search-container">
      <div id="search-navbar" class="navbar-static-top col-md-6" role="navigation">
        <div class="navbar-header">
          <% if user_signed_in? %>
              <%= render partial: '/shared/search_form' %>
          <% end %>
        </div>
        <br><br>
        <div id="navigation_tabs">
          <% if user_signed_in? %>
              <% get_institution_for_tabs %>
              <ul class="nav nav-tabs">
                <li id="inst_tab"><%= link_to 'Institution', institution_path(@inst) %></li>
                <li id="io_tab"><%= link_to 'Objects', intellectual_objects_path(@inst, sort: 'date') %></li>
                <li id="gf_tab"><%= link_to 'Files', institution_files_path(@inst, sort: 'date') %></li>
                <li id="pe_tab"><%= link_to 'Events', institution_events_path(@inst) %></li>
                <li id="wi_tab"><%= link_to 'Work Items', work_items_path %></li>
                <% if current_user.admin? || current_user.institutional_admin? %>
                    <li id="alert_tab"><%= link_to 'Alerts', alerts_path %></li>
                <% end %>
                <li id="rep_tab"><%= link_to 'Reports', institution_timeline_report_path(@inst.identifier) %></li>
              </ul>
          <% end %>
          <script>tabbed_nav('<%= params[:controller]%>');</script>
        </div>
      </div>
    </div>

    <div class="collapse navbar-collapse col-md-3" id="user-util-collapse">
      <% if user_signed_in? %>
          <%= render partial: '/user_util_links' %>
      <% else %>
          <%= render partial: '/user_sign_in_links' %>
      <% end %>
    </div>

  </div>

</div>

app/views/shared/_password_popup.html.erb
<div id="passPopoverDiv">
  <p><span class="badge badge-danger">Attention!</span> Passwords must be at least 10 characters long but we
    recommend that they be even longer. For tips on creating strong passwords,
    please see this helpful comic:
    <a href='https://xkcd.com/936/' target="_blank" title='xkcd passwords'>https://xkcd.com/936/</a></p>
</div>

app/views/shared/_search_breadcrumb.html.erb
<div id="searchBreadcrumb" class="clearfix">

</div>

<% unless (params[:q].nil? || params[:q] == '%' || params[:q] == '*') && @selected == {} %>
    <div id="appliedParams" class="clearfix constraints-container">
      <div class="pull-right">
        <a class="catalog_startOverLink btn btn-sm btn-text" href="<%= start_over_link(params[:controller]) %>" id="startOverLink">Start Over</a>
      </div>
      <span class="constraints-label">You searched for: </span>
      <% unless params[:object_type].nil? || params[:object_type] == '' || params[:object_type] == 'All Types' %>
        <span class="btn-group appliedFilter constraint filter">
          <span class="constraint-value btn btn-sm btn-default btn-disabled">
            <span class="filterName">Result Type:</span>
            <span class="filterValue"><%= params[:object_type] %></span>
          </span>
        </span>
      <% end %>
      <% unless params[:q].nil? || params[:q] == '' || params[:q] == '%' || params[:q] == '*' %>
      <span class="btn-group appliedFilter constraint query">
        <span class="constraint-value btn btn-sm btn-default btn-disabled">
          <% if params[:search_field].nil? || params[:search_field] == '' || params[:search_field] == 'All Fields' %>
            <span class="filterValue"><%= params[:q] %></span>
          <% else %>
            <span class="filterName"><%= params[:search_field] %>:</span>
            <span class="filterValue"><%= params[:q] %></span>
          <% end %>
        </span>
        <a class="btn btn-default btn-sm remove" href="<%=url_for(params.permit(Pharos::Application::PARAMS_HASH).except :q)%>">
          <span class="glyphicon glyphicon-remove"></span>
          <span class="sr-only">Remove constraint <%= params[:q] %></span>
        </a>
      </span>
      <% end %>
      <% if @selected %>
          <% @selected.each do |key, value| %>

            <% if key == :state %>
                  <span class="btn-group appliedFilter constraint filter">
                    <span class="constraint-value btn btn-sm btn-default btn-disabled">
                      <span class="filterName"><%= key.capitalize %>:</span>
                      <span class="filterValue"><%= value %></span>
                    </span>
                    <a class="btn btn-default btn-sm remove" href="<%= current_path('state', 'all')%>">
                      <span class="glyphicon glyphicon-remove"></span>
                      <span class="sr-only">Remove constraint <%= key %>: <%= value %></span>
                    </a>
                  </span>
            <% else %>
                  <span class="btn-group appliedFilter constraint filter">
                    <span class="constraint-value btn btn-sm btn-default btn-disabled">
                      <% if key == :institution %>
                          <span class="filterName"><%= key.capitalize %>:</span>
                          <span class="filterValue"><%= Institution.find(value).name %></span>
                      <% elsif key == :access %>
                          <span class="filterName"><%= key.capitalize %>:</span>
                          <span class="filterValue"><%= value.capitalize %></span>
                      <% elsif key == :item_action %>
                          <span class="filterName">Action:</span>
                          <span class="filterValue"><%= value.capitalize %></span>
                      <% elsif key == :file_format %>
                          <span class="filterName">Format:</span>
                          <span class="filterValue"><%= value %></span>
                      <% elsif key == :object_association %>
                          <span class="filterName">Associated Object:</span>
                          <span class="filterValue"><%= IntellectualObject.find(value).identifier %></span>
                      <% elsif key == :file_association %>
                          <span class="filterName">Associated File:</span>
                          <span class="filterValue"><%= GenericFile.find(value).identifier %></span>
                      <% elsif key == :outcome %>
                          <span class="filterName">Outcome:</span>
                          <span class="filterValue"><%= value.capitalize %></span>
                      <% elsif key == :event_type %>
                          <span class="filterName">Event Type:</span>
                          <span class="filterValue"><%= value.capitalize %></span>
                      <% else %>
                          <span class="filterName"><%= key.capitalize %>:</span>
                          <span class="filterValue"><%= value %></span>
                      <% end %>
                    </span>
                    <a class="btn btn-default btn-sm remove" href="<%=url_for(params.permit(Pharos::Application::PARAMS_HASH).except key)%>">
                      <span class="glyphicon glyphicon-remove"></span>
                      <span class="sr-only">Remove constraint <%= key %>: <%= value %></span>
                    </a>
                  </span>
            <% end %>
          <% end %>
      <% end %>
    </div>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_tag method: 'get', action: 'search', controller: '/catalog' do %>
    <div class="input-group" id="search">

      <span class="input-group-addon">
        <label for="search_field" class="sr-only">Search</label>
        <% if current_user.admin? %>
            <%= select_tag :object_type, options_for_select(['Intellectual Objects', 'Generic Files', 'Work Items', 'Premis Events'], params[:object_type]), onchange: 'configureDropDownLists();' %>
        <% else %>
            <%= select_tag :object_type, options_for_select(['Intellectual Objects', 'Generic Files', 'Work Items', 'Premis Events'], params[:object_type]), onchange: 'configureDropDownLists();' %>
        <% end %>
        <%= select_tag :search_field, options_for_select([], params[:search_field]) %>

        <% if params[:search_field] %>
          <%= javascript_tag do %>
                configureDropDownLists();
                adjustSearchField('<%= params[:search_field] %>');
          <% end %>
        <% else %>
          <%= javascript_tag do %>
                configureDropDownLists();
          <% end %>
        <% end %>

      </span>
      <label for="q" class="sr-only">Search Box</label>
      <%= text_field_tag :q, params[:q], :placeholder => 'Search...', :class => 'search_q q form-control', :id => 'q' %>

      <span class="input-group-btn" class="span5">
        <button type="submit" class="btn btn-primary search-btn" id="search-btn">
          <span class="submit-search-text">Search</span>
          <span class="glyphicon glyphicon-search"></span>
        </button>
        </span>
    </div>
<% end %>

app/views/shared/_search_results.html.erb
<h2 class="sr-only">Search Results</h2>
<div id="documents">
    <% counter = @first_number %>
    <% @paged_results.each do |current| %>
        <% if current.is_a?(IntellectualObject) %>
            <%= render 'shared/individual_results/object_result', counter: counter, current: current %>
        <% elsif current.is_a?(GenericFile) %>
            <%= render 'shared/individual_results/file_result', counter: counter, current: current %>
        <% elsif current.is_a?(WorkItem) %>
            <%= render 'shared/individual_results/item_result', counter: counter, current: current %>
        <% elsif current.is_a?(PremisEvent) %>
          <%= render 'shared/individual_results/event_result', counter: counter, current: current %>
        <% elsif current.is_a?(BulkDeleteJob) %>
          <%= render 'shared/individual_results/bulk_delete_job_result', counter: counter, current: current %>
        <% end %>
        <% counter = counter+1 %>
        <hr>
    <% end %>
</div>

app/views/shared/_sort_and_per_page.html.erb
<div id="sortAndPerPage" class="clearfix">

  <span class="page_links">
    <% if @previous.nil? %>
        « Previous |
    <% else %>
        « <a href="<%= @previous %>" rel="previous"> Previous</a> |
    <% end %>
    <span class="page_entries">
       <strong><%= @first_number %></strong> - <strong><%= @second_number %></strong> of <strong><%= @count %></strong>
    </span>
    <% if @next.nil? %>
        | Next »
    <% else %>
        | <a href="<%= @next %>" rel="next">Next</a> »
    <% end %>

  </span>

  <span class="search-widgets pull-right">
    <span class="sr-only"><%= 'Per Page' %></span>

    <div id="per_page-dropdown" class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <%= link_to(t(:'Per page', :count => @page), "#") %>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a href="<%= current_path('per_page', '10') %>">10</a></li>
        <li><a href="<%= current_path('per_page', '20') %>">20</a></li>
        <li><a href="<%= current_path('per_page', '50') %>">50</a></li>
        <li><a href="<%= current_path('per_page', '100') %>">100</a></li>
      </ul>
    </div>

    <div id="sort-dropdown" class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <a href="#">Sort by </a>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><a href="<%= current_path('sort', 'date') %>">Last Updated</a></li>
        <li><a href="<%= current_path('sort', 'name') %>">Name</a></li>
        <% if current_user.admin? %>
            <li><a href="<%= current_path('sort', 'institution') %>">Institution</a></li>
        <% end %>
      </ul>
    </div>
  </span>
</div>

app/views/shared/_user_util_links.html.erb
<ul class="nav pull-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.to_s %></strong> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <% if current_user.admin? or current_user.institutional_admin? %>
          <li><%= link_to 'New User', new_user_path %></li>
          <li class="divider"></li>
      <% end %>
      <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
      <li class="divider"></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    </ul>
  </li>
</ul>

app/views/shared/_work_items.html.erb
<h4>Most Recent Work Items for <%= @institution.name %></h4>
<table class="table">
    <thead>
  <tr>
      <th>Name</th>
      <th>Institution</th>
      <th>Processed</th>
      <th>Size</th>
      <th>Action</th>
      <th>Stage</th>
      <th>Status</th>
    </tr>
  </thead>
    <tbody>
  <% if @items.nil? || @items.empty? %>
          No Work Items to display.
      <% else %>
          <% @items.each do |item| %>
                  <tr class="<%= item.status %>">
              <td><%= link_to item.name, work_item_path(id: item.id) %></td>
              <td><%= item.institution.identifier %></td>
              <td><%= pretty_date(item.date) %></td>
              <td><%= number_to_human_size(item.size) %></td>
              <td><%= item.action %></td>
              <td><%= item.stage %></td>
              <td><%= item.status %></td>
            </tr>
              <% end %>
      <% end %>
  </tbody>
</table>

app/views/shared/_zero_results.html.erb
<h2><%= 'No Results' %></h2>
<div id="documents" class="noresults">
  <h3><%= 'Try modifying your search.' %></h3>
  <ul>
    <li><%= 'Consider using fewer keywords.' %></li>
  </ul>
</div>