config/routes.rb
  get 'member-api/v2/files/restore/:generic_file_identifier', to: 'generic_files#restore', format: :json, generic_file_identifier: file_ptrn
  put 'api/v2/files/restore/:generic_file_identifier', to: 'generic_files#restore', format: :json, generic_file_identifier: file_ptrn


  # INSTITUTIONS (API)
  # resources :institutions doesn't like this route for #show, because it interprets .edu/.org/.com as an 'unknown format'
  get 'api/v2/institutions/:institution_identifier', to: 'institutions#show', format: [:json], institution_identifier: institution_ptrn

  # PREMIS EVENT ROUTES
  uuid_pattern = /([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}){1}/
  get '/api/v2/events/:identifier', to: 'premis_events#show', format: [:json], identifier: uuid_pattern
  get 'events/:file_identifier', to: 'premis_events#index', format: [:json, :html], file_identifier: file_ptrn, as: :generic_file_events
  get 'events/:object_identifier', to: 'premis_events#index', format: [:json, :html], object_identifier: object_ptrn, as: :intellectual_object_events
  get 'events/:institution_identifier', to: 'premis_events#index', format: [:json, :html], institution_identifier: institution_ptrn, as: :institution_events
  get 'events/:id', to: 'premis_events#show', format: [:json, :html], as: :premis_event
  get '/api/v2/events', to: 'premis_events#index', format: [:json, :html]
  post '/api/v2/events', to: 'premis_events#create', format: :json
  get '/api/v2/events/:id', to: 'premis_events#show', format: [:json, :html]
  get 'member-api/v2/events/:file_identifier', to: 'premis_events#index', format: :json, file_identifier: file_ptrn
  get 'member-api/v2/events/:object_identifier', to: 'premis_events#index', format: :json, object_identifier: object_ptrn
  get 'member-api/v2/events/:institution_identifier', to: 'premis_events#index', format: :json, institution_identifier: institution_ptrn
  get 'notifications/failed_fixity', to: 'premis_events#notify_of_failed_fixity', format: :json
  get '/api/v2/notifications/failed_fixity', to: 'premis_events#notify_of_failed_fixity', format: :json

  # WORK ITEM ROUTES
  resources :work_items, only: [:index, :create, :show, :update, :edit], format: [:html, :json], path: 'items'
  put 'items/', to: 'work_items#update', format: :json
  resources :work_items, path: '/api/v2/items'
  resources :work_items, only: [:index], path: 'member-api/v2/items', format: [:json, :html]
  get '/api/v2/items/:etag/:name/:bag_date', to: 'work_items#show', as: :work_item_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  put '/api/v2/items/:etag/:name/:bag_date', to: 'work_items#update', format: 'json', as: :work_item_api_update_by_etag, name: /[^\/]*/, bag_date: /[^\/]*/
  get 'items/items_for_restore', to: 'work_items#items_for_restore', format: :json
  get 'items/items_for_delete', to: 'work_items#items_for_delete', format: :json
  get 'items/ingested_since', to: 'work_items#ingested_since', format: :json
  get 'items/set_restoration_status', to: 'work_items#set_restoration_status', format: :json
  get 'api/v2/items/search', to: 'work_items#api_search', format: :json
  get 'items/:id/requeue', to: 'work_items#requeue', format: [:json, :html], as: :requeue_work_item
  get 'notifications/successful_restoration', to: 'work_items#notify_of_successful_restoration', format: :json
  get '/api/v2/notifications/successful_restoration', to: 'work_items#notify_of_successful_restoration', format: :json
  get 'notifications/spot_test_restoration/:id', to: 'work_items#spot_test_restoration', format: :json
  get '/api/v2/notifications/spot_test_restoration/:id', to: 'work_items#spot_test_restoration', format: :json

  # WORK ITEM STATE ROUTES
  #resources :work_item_states, path: 'item_state', only: [:show, :update, :create], format: :json, param: :work_item_id
  #resources :work_item_states, path: '/api/v2/item_state', only: [:show, :update, :create], format: :json, param: :work_item_id
  post '/api/v2/item_state', to: 'work_item_states#create', format: :json
  put '/api/v2/item_state/:id', to: 'work_item_states#update', format: :json
  get '/api/v2/item_state/:id', to: 'work_item_states#show', format: :json

  # CHECKSUM ROUTES
  get '/api/v2/checksums', to: 'checksums#index', format: :json
  get '/api/v2/checksums/:id', to: 'checksums#show', format: :json
  post '/api/v2/checksums/:generic_file_identifier', to: 'checksums#create', format: :json, generic_file_identifier: /.*/

  # CATALOG ROUTES
  post 'search/', to: 'catalog#search', format: [:json, :html], as: :search
  get 'search/', to: 'catalog#search', format: [:json, :html]
  get 'api/v2/search', to: 'catalog#search', format: [:json, :html], as: :api_search
  get 'feed', to: 'catalog#feed', format: :rss, as: :rss_feed

  # REPORT ROUTES
  get 'reports/:identifier', to: 'reports#index', format: [:json, :html], as: :reports, identifier: institution_ptrn
  get 'reports/overview/:identifier', to: 'reports#overview', format: [:json, :html, :pdf], as: :institution_overview, identifier: institution_ptrn
  get 'reports/general/:identifier', to: 'reports#general', format: [:json, :html, :pdf], as: :institution_general_report, identifier: institution_ptrn
  get 'reports/cost/:identifier', to: 'reports#cost', format: [:json, :html, :pdf], as: :institution_cost_report, identifier: institution_ptrn
  get 'reports/subscribers/:identifier', to: 'reports#subscribers', format: [:json, :html, :pdf], as: :institution_subscribers_report, identifier: institution_ptrn
  get 'reports/timeline/:identifier', to: 'reports#timeline', format: [:json, :html, :pdf], as: :institution_timeline_report, identifier: institution_ptrn
  get 'reports/mimetype/:identifier', to: 'reports#mimetype', format: [:json, :html, :pdf], as: :institution_mimetype_report, identifier: institution_ptrn
  get 'reports/institution_breakdown', to: 'reports#institution_breakdown', format: [:json, :html, :pdf], as: :institution_breakdown
  get 'reports/object_report/:intellectual_object_identifier', to: 'reports#object_report', format: [:json, :html], as: :object_report, intellectual_object_identifier: object_ptrn

  # ALERT ROUTES
  get 'alerts/', to: 'alerts#index', format: [:json, :html], as: :alerts
  get 'alerts/summary', to: 'alerts#summary', format: [:json, :html], as: :alerts_summary

  # EMAIL ROUTES
  resources :emails, path: 'email_logs', only: [:index, :show], format: [:json]

  # SNAPSHOT ROUTES
  resources :snapshots, path: 'snapshots', only: [:index, :show], format: [:json, :html]

  # BULK DELETE JOB ROUTES
  resources :bulk_delete_jobs, path: 'bulk_delete_jobs', only: [:index, :show], format: [:json, :html]
  resources :bulk_delete_jobs, path: 'api/v2/bulk_delete_jobs', only: [:index, :show], format: :json

  # USER ROUTES
  devise_for :users,
  pathnames: {
      verify_authy: '/verify-token',
      enable_authy: '/enable-authy',
      verify_authy_installation: '/verify-installation'
  }

  resources :users do
    patch 'update_password', on: :collection
    get 'edit_password', on: :member
    patch 'generate_api_key', on: :member
  end
  get 'users/:id/admin_password_reset', to: 'users#admin_password_reset', as: :admin_password_reset_user
  get 'users/:id/forced_password_update', to: 'users#forced_password_update', as: :user_forced_password_update
  get 'users/:id/deactivate', to: 'users#deactivate', as: :deactivate_user
  get 'users/:id/reactivate', to: 'users#reactivate', as: :reactivate_user
  get '/vacuum', to: 'users#vacuum', format: [:json, :html], as: :vacuum
  get '/api/v2/vacuum', to: 'users#vacuum', format: [:json, :html], as: :api_vacuum
  get '/notifications/stale_users', to: 'users#stale_user_notification', format: [:json, :html], as: :stale_users
  get '/api/v2/notifications/stale_users', to: 'users#stale_user_notification', format: [:json, :html], as: :api_stale_users
  get '/account_confirmations', to: 'users#account_confirmations', format: [:json, :html], as: :account_confirmations
  get '/api/v2/account_confirmations', to: 'users#account_confirmations', format: [:json, :html], as: :api_account_confirmations
  get '/users/:id/individual_account_confirmation', to: 'users#indiv_confirmation_email', format: [:json, :html], as: :indiv_confirmation_email
  get '/api/v2/users/:id/individual_account_confirmation', to: 'users#indiv_confirmation_email', format: [:json, :html], as: :api_indiv_confirmation_email
  get '/users/:id/confirm_account', to: 'users#confirm_account', format: [:json, :html], as: :confirm_account
  get '/api/v2/users/:id/confirm_account', to: 'users#confirm_account', format: [:json, :html], as: :api_confirm_account
  get 'users/:id/enable_otp', to: 'users#enable_otp', as: :users_enable_otp
  get 'users/:id/disable_otp', to: 'users#disable_otp', as: :users_disable_otp
  get 'users/:id/register_authy', to: 'users#register_authy_user', as: :users_register_for_authy
  get 'users/:id/change_authy_phone_number', to: 'users#change_authy_phone_number', as: :user_authy_number
  get 'users/:id/verify_twofa', to: 'users#verify_twofa', as: :users_verify_twofa
  get 'users/:id/backup_codes', to: 'users#generate_backup_codes', as: :backup_codes
  get 'users/:id/two_factor_text_link', to: 'users#two_factor_text_link', as: :twofa_text
  get 'users/:id/verify_email', to: 'users#verify_email', as: :email_verification
  get 'users/:id/email_confirmation', to: 'users#email_confirmation', as: :email_confirmation

  resources :verifications, only: [:edit, :update]
  get 'verifications/login', to: 'verifications#login', as: :verification_login
  get 'verifications/enter_backup/:id', to: 'verifications#enter_backup', as: :enter_backup_verification
  put 'verifications/check_backup/:id', to: 'verifications#check_backup', as: :check_backup_verification

  #get '/verification_callback', to: 'application#callback', as: :verification_callback

  authenticated :user do
    root to: 'institutions#show', as: 'authenticated_root'
  end

  root :to => 'institutions#show'

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    authorize current_user, :alert_index?
    params[:since] = (DateTime.now - 24.hours) unless params[:since]
    params[:type] = 'all' unless params[:type]
    respond_to do |format|
      format.json {
        get_index_lists(params[:since])
        render json: @alerts_list.to_json
      }
      format.html {
        params[:type] = 'all'
        get_index_lists(params[:since])
        render 'index'
      }
    end
  end

  def summary
    authorize current_user, :alert_summary?
    params[:since] = (DateTime.now - 24.hours) unless params[:since]
    get_summary_counts(params[:since])
    respond_to do |format|
      format.json { render json: @alerts_summary.to_json }
      format.html { }
    end
  end

  private

  def get_index_lists(datetime)
    @alerts_list = {}
    case params[:type]
      when 'fixity'
        @alerts_list[:failed_fixity_checks] = PremisEvent.failed_fixity_checks(datetime, current_user)
      when 'ingest'
        @alerts_list[:failed_ingests] = WorkItem.failed_action(datetime, Pharos::Application::PHAROS_ACTIONS['ingest'], current_user)
      when 'restore'
        @alerts_list[:failed_restorations] = WorkItem.failed_action(datetime, Pharos::Application::PHAROS_ACTIONS['restore'], current_user)
      when 'delete'
        @alerts_list[:failed_deletions] = WorkItem.failed_action(datetime, Pharos::Application::PHAROS_ACTIONS['delete'], current_user)
      when 'stalled_wi'
        @alerts_list[:stalled_work_items] = WorkItem.stalled_items(current_user)
      when 'all'
        @alerts_list[:failed_fixity_checks] = PremisEvent.failed_fixity_checks(datetime, current_user)
        @alerts_list[:failed_ingests] = WorkItem.failed_action(datetime, Pharos::Application::PHAROS_ACTIONS['ingest'], current_user)
        @alerts_list[:failed_restorations] = WorkItem.failed_action(datetime, Pharos::Application::PHAROS_ACTIONS['restore'], current_user)
        @alerts_list[:failed_deletions] = WorkItem.failed_action(datetime, Pharos::Application::PHAROS_ACTIONS['delete'], current_user)
        @alerts_list[:stalled_work_items] = WorkItem.stalled_items(current_user)
    end
  end

  def get_summary_counts(datetime)
    @alerts_summary = {}
    @alerts_summary[:failed_fixity_count] = PremisEvent.failed_fixity_check_count(datetime, current_user)
    @alerts_summary[:failed_ingest_count] = WorkItem.failed_action_count(datetime, Pharos::Application::PHAROS_ACTIONS['ingest'], current_user)
    @alerts_summary[:failed_restoration_count] = WorkItem.failed_action_count(datetime, Pharos::Application::PHAROS_ACTIONS['restore'], current_user)
    @alerts_summary[:failed_deletion_count] = WorkItem.failed_action_count(datetime, Pharos::Application::PHAROS_ACTIONS['delete'], current_user)
    @alerts_summary[:stalled_work_item_count] = WorkItem.stalled_items_count(current_user)
  end

end

app/views/alerts/_premis_event_results.html.erb
<table class="table">
  <thead>
  <tr>
    <th>File Identifier</th>
    <th>Event Identifier</th>
    <th>Date & Time</th>
  </tr>
  </thead>
  <tbody>
  <% events.each do |event| %>
      <tr>
        <td><a href="<%= generic_file_path(generic_file_identifier: event.generic_file_identifier) %>" ><%= truncate(event.generic_file_identifier, length: 80) %></a></td>
        <td><%= event.identifier %></td>
        <td><%= pretty_date(event.date_time) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/alerts/_work_item_results.html.erb
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Institution</th>
    <th>Processed</th>
    <th>Action</th>
    <th>Stage</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <% work_items.each do |item| %>
      <tr class=>
        <td><% if item.action == Pharos::Application::PHAROS_ACTIONS['delete'] %>
              <% unless item.generic_file_identifier.nil? %>
                  <a href="<%= work_item_path(id: item.id) %>" ><%= truncate(item.generic_file_identifier, length: 70) %></a>
              <% else %>
                  <a href="<%= work_item_path(id: item.id) %>" ><%= truncate(item.object_identifier, length: 70) %></a>
              <% end %>
          <% elsif !item.object_identifier.blank? %>
              <a href="<%= work_item_path(id: item.id) %>" ><%= truncate(item.object_identifier, length: 70) %></a>
          <% else %>
              <a href="<%= work_item_path(id: item.id) %>" ><%= truncate(item.name, length: 70) %></a>
          <% end %>
        </td>
        <td><%= item.institution.identifier %></td>
        <td><%= pretty_date(item.date) %></td>
        <td><%= item.action %></td>
        <td><%= item.stage %></td>
        <td><%= item.status %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/alerts/index.html.erb
<% @title = 'Alerts' %>

<div class="page-header">
  <h1 id="alerts_title">Alerts</h1>
  <%= link_to alerts_summary_path, {class: 'btn doc-action-btn btn-normal', id: 'alert-summary-button'} do %>
      <i class="glyphicon glyphicon-list"></i> Summary of Alerts
  <% end %>
</div>

<ul class="nav nav-tabs" id="alert_index_tabs">
  <li><a href="#fixity" data-toggle="tab">Failed Fixity Checks</a></li>
  <li><a href="#ingest" data-toggle="tab">Failed Ingests</a></li>
  <li><a href="#restore" data-toggle="tab">Failed Restorations</a></li>
  <li><a href="#delete" data-toggle="tab">Failed Deletions</a></li>
  <li><a href="#stalled" data-toggle="tab">Stalled Work Items</a></li>
</ul>

<div class="tab-content" id="inst_show_content">
  <div class="tab-pane" id="fixity">
    <br><p>Total Failed Fixity Checks: <%= @alerts_list[:failed_fixity_checks].count %></p>
    <%= render 'premis_event_results', events: @alerts_list[:failed_fixity_checks] %>
  </div>

  <div class="tab-pane" id="ingest">
    <br><p>Total Failed Ingests: <%= @alerts_list[:failed_ingests].count %></p>
    <%= render 'work_item_results', work_items: @alerts_list[:failed_ingests] %>
  </div>

  <div class="tab-pane" id="restore">
    <br><p>Total Failed Restorations: <%= @alerts_list[:failed_restorations].count %></p>
    <%= render 'work_item_results', work_items: @alerts_list[:failed_restorations] %>
  </div>

  <div class="tab-pane" id="delete">
    <br><p>Total Failed Deletions: <%= @alerts_list[:failed_deletions].count %></p>
    <%= render 'work_item_results', work_items: @alerts_list[:failed_deletions] %>
  </div>

  <div class="tab-pane" id="stalled">
    <br><p>Total Stalled Work Items: <%= @alerts_list[:stalled_work_items].count %></p>
    <%= render 'work_item_results', work_items: @alerts_list[:stalled_work_items] %>
  </div>
</div>

app/views/alerts/summary.html.erb
<% @title = 'Alerts Summary' %>

<div id="content" class="col-md-9 col-sm-8">
  <h1>Alerts Summary</h1>
  <dl class="dl-horizontal alert_summary">
    <dt>Failed Fixity Checks</dt>
    <dd><%= @alerts_summary[:failed_fixity_count] %></dd>
    <dt>Failed Ingests</dt>
    <dd><%= @alerts_summary[:failed_ingest_count] %></dd>
    <dt>Failed Restorations</dt>
    <dd><%= @alerts_summary[:failed_restoration_count] %></dd>
    <dt>Failed Deletions</dt>
    <dd><%= @alerts_summary[:failed_deletion_count] %></dd>
    <dt>Stalled Work Items</dt>
    <dd><%= @alerts_summary[:stalled_work_item_count] %></dd>
  </dl>
</div>