config/routes.rb
Rails.application.routes.draw do

  # INSTITUTION ROUTES
  institution_ptrn = /(?:[a-zA-Z0-9\-_]+)(?:\.[a-zA-Z]+)+/
  resources :institutions, format: [:json, :html], param: :institution_identifier, institution_identifier: institution_ptrn
  resources :institutions, only: [:index], format: :json, param: :institution_identifier, institution_identifier: institution_ptrn, path: 'api/v2/institutions'
  get ':institution_identifier/single_snapshot', to: 'institutions#single_snapshot', format: [:html, :json], institution_identifier: institution_ptrn, as: :institution_snapshot
  get 'api/v2/:institution_identifier/single_snapshot', to: 'institutions#single_snapshot', format: [:html, :json], institution_identifier: institution_ptrn, as: :api_institution_snapshot
  get '/group_snapshot', to: 'institutions#group_snapshot', format: [:html, :json], as: :group_snapshot
  get 'api/v2/group_snapshot', to: 'institutions#group_snapshot', format: [:html, :json], as: :api_group_snapshot
  get '/:institution_identifier/deactivate', to: 'institutions#deactivate', as: :deactivate_institution, institution_identifier: institution_ptrn
  get '/:institution_identifier/reactivate', to: 'institutions#reactivate', as: :reactivate_institution, institution_identifier: institution_ptrn
  get '/:institution_identifier/enable_otp', to: 'institutions#enable_otp', as: :enable_otp_institution, format: [:html, :json], institution_identifier: institution_ptrn
  get '/:institution_identifier/disable_otp', to: 'institutions#disable_otp', as: :disable_otp_institution, format: [:html, :json], institution_identifier: institution_ptrn
  post 'api/v2/:institution_identifier/trigger_bulk_delete', to: 'institutions#trigger_bulk_delete', as: :api_bulk_deletion, format: :json, institution_identifier: institution_ptrn
  get '/:institution_identifier/confirm_bulk_delete_institution', to: 'institutions#partial_confirmation_bulk_delete', as: :bulk_deletion_institutional_confirmation, format: [:html, :json], institution_identifier: institution_ptrn
  post 'api/v2/:institution_identifier/confirm_bulk_delete_institution', to: 'institutions#partial_confirmation_bulk_delete', as: :api_bulk_deletion_institutional_confirmation, format: :json, institution_identifier: institution_ptrn
  get '/:institution_identifier/confirm_bulk_delete_admin', to: 'institutions#final_confirmation_bulk_delete', as: :bulk_deletion_admin_confirmation, format: [:html, :json], institution_identifier: institution_ptrn
  post 'api/v2/:institution_identifier/confirm_bulk_delete_admin', to: 'institutions#final_confirmation_bulk_delete', as: :api_bulk_deletion_admin_confirmation, format: :json, institution_identifier: institution_ptrn
  get '/:institution_identifier/finished_bulk_delete', to: 'institutions#finished_bulk_delete', as: :bulk_deletion_finished, format: [:html, :json], institution_identifier: institution_ptrn
  post 'api/v2/:institution_identifier/finished_bulk_delete', to: 'institutions#finished_bulk_delete', as: :api_bulk_deletion_finished, format: :json, institution_identifier: institution_ptrn
  get '/notifications/deletion', to: 'institutions#deletion_notifications', as: :institution_deletion_notifications, format: [:html, :json]
  get 'api/v2/notifications/deletion', to: 'institutions#deletion_notifications', as: :api_institution_deletion_notifications, format: [:html, :json]
  get '/:institution_identifier/mass_forced_password_update', to: 'institutions#mass_forced_password_update', as: :mass_forced_password_update, format: [:html, :json], institution_identifier: institution_ptrn
  get 'api/v2/:institution_identifier/mass_forced_password_update', to: 'institutions#mass_forced_password_update', as: :api_mass_forced_password_update, format: [:html, :json], institution_identifier: institution_ptrn

  # Admin URL for monthly deposit report
  get 'api/v2/deposit_summary', to: 'institutions#deposit_summary', as: :institution_deposit_summary, format: [:json]


  # INTELLECTUAL OBJECT ROUTES
  object_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org|\.museum)(\%|\/)[\w\-\.\%\?\=\(\)\:\#\[\]\!\$\&\'\*\+\,\;\_\~\ \p{L}]+/
  resources :intellectual_objects, only: [:show, :edit, :update, :destroy], format: [:json, :html], param: :intellectual_object_identifier, intellectual_object_identifier: object_ptrn, path: 'objects'
  get 'objects/:intellectual_object_identifier/restore', to: 'intellectual_objects#restore', format: [:json, :html], intellectual_object_identifier: object_ptrn, as: :intellectual_object_restore
  get 'objects', to: 'intellectual_objects#index', format: [:json, :html]
  get 'objects/:institution_identifier', to: 'intellectual_objects#index', format: [:json, :html], institution_identifier: institution_ptrn, as: :intellectual_objects
  resources :intellectual_objects, only: [:show, :update, :destroy], format: :json, param: :intellectual_object_identifier, intellectual_object_identifier: object_ptrn, path: 'api/v2/objects'
  get 'api/v2/objects/:institution_identifier', to: 'intellectual_objects#index', format: [:json, :html], institution_identifier: institution_ptrn
  get 'api/v2/objects', to: 'intellectual_objects#index', format: [:json, :html]
  post 'api/v2/objects/:institution_identifier', to: 'intellectual_objects#create', format: :json, institution_identifier: institution_ptrn
  get 'member-api/v2/objects/:institution_identifier', to: 'intellectual_objects#index', format: [:json, :html], institution_identifier: institution_ptrn
  get 'member-api/v2/objects/', to: 'intellectual_objects#index', format: [:json, :html]
  get 'member-api/v2/objects/:intellectual_object_identifier/restore', to: 'intellectual_objects#restore', format: :json, intellectual_object_identifier: object_ptrn
  put 'api/v2/objects/:intellectual_object_identifier/restore', to: 'intellectual_objects#restore', format: :json, intellectual_object_identifier: object_ptrn
  delete 'api/v2/objects/:intellectual_object_identifier/delete', to: 'intellectual_objects#destroy', format: :json, intellectual_object_identifier: object_ptrn
  delete 'objects/:intellectual_object_identifier/confirm_delete', to: 'intellectual_objects#confirm_destroy', format: [:html, :json], intellectual_object_identifier: object_ptrn, as: :object_confirm_destroy
  delete 'api/v2/objects/:intellectual_object_identifier/confirm_delete', to: 'intellectual_objects#confirm_destroy', format: :json, intellectual_object_identifier: object_ptrn, as: :api_object_confirm_destroy
  get 'objects/:intellectual_object_identifier/confirm_delete', to: 'intellectual_objects#confirm_destroy', format: [:html, :json], intellectual_object_identifier: object_ptrn, as: :get_object_confirm_destroy
  get 'api/v2/objects/:intellectual_object_identifier/confirm_delete', to: 'intellectual_objects#confirm_destroy', format: :json, intellectual_object_identifier: object_ptrn, as: :get_api_object_confirm_destroy
  get 'objects/:intellectual_object_identifier/finish_delete', to: 'intellectual_objects#finished_destroy', format: [:html, :json], intellectual_object_identifier: object_ptrn, as: :get_object_finish_destroy
  get 'api/v2/objects/:intellectual_object_identifier/finish_delete', to: 'intellectual_objects#finished_destroy', format: :json, intellectual_object_identifier: object_ptrn, as: :get_api_object_finish_destroy

  # GENERIC FILE ROUTES
  file_ptrn = /(\w+\.)*\w+(\.edu|\.com|\.org|\.museum)(\%2[Ff]|\/)+[\w\-\/\.\%\?\=\(\)\:\#\[\]\!\$\&\'\*\+\,\;\_\~\ \p{L}]+(\%2[fF]|\/)+[\w\-\/\.\%\@\?\=\(\)\:\#\[\]\!\$\&\'\*\+\,\;\_\~\ \p{L}]+/
  resources :generic_files, only: [:show, :update, :destroy], format: [:json, :html], defaults: { format: :html }, param: :generic_file_identifier, generic_file_identifier: file_ptrn, path: 'files'
  resources :generic_files, only: [:show, :update, :destroy], format: [:json, :html], defaults: { format: :json }, param: :generic_file_identifier, generic_file_identifier: file_ptrn, path: 'api/v2/files'
  get '/api/v2/files/:institution_identifier', to: 'generic_files#index', format: [:json, :html], institution_identifier: institution_ptrn, as: :institution_files_api
  get '/api/v2/files/:intellectual_object_identifier', to: 'generic_files#index', format: [:json, :html], intellectual_object_identifier: object_ptrn, as: :intellectual_object_files_api
  get '/api/v2/files/', to: 'generic_files#index', format: [:json], as: :generic_files_admin_list
  get 'files/:institution_identifier', to: 'generic_files#index', format: [:json, :html], institution_identifier: institution_ptrn, as: :institution_files
  get 'files/:intellectual_object_identifier', to: 'generic_files#index', format: [:json, :html], intellectual_object_identifier: object_ptrn, as: :intellectual_object_files
  post '/api/v2/files/:intellectual_object_id/create_batch', to: 'generic_files#create_batch', format: :json
  post '/api/v2/files/:intellectual_object_identifier', to: 'generic_files#create', format: :json, intellectual_object_identifier: object_ptrn
  put '/api/v2/files/:intellectual_object_identifier', to: 'generic_files#update', format: :json, intellectual_object_identifier: object_ptrn
  resources :generic_files, only: [:index, :create], format: [:json, :html], param: :intellectual_object_identifier, intellectual_object_identifier: object_ptrn, path: 'api/v2/files'
  get 'member-api/v2/files/:intellectual_object_identifier', to: 'generic_files#index', format: :json, intellectual_object_identifier: object_ptrn
  get 'member-api/v2/files/:institution_identifier', to: 'generic_files#index', format: :json, institution_identifier: institution_ptrn
  delete 'files/confirm_delete/:generic_file_identifier', to: 'generic_files#confirm_destroy', format: [:html, :json], generic_file_identifier: file_ptrn, as: :file_confirm_destroy
  delete 'api/v2/files/confirm_delete/:generic_file_identifier', to: 'generic_files#confirm_destroy', format: [:html, :json], generic_file_identifier: file_ptrn, as: :api_file_confirm_destroy

app/helpers/intellectual_objects_helper.rb
module IntellectualObjectsHelper

end

app/views/intellectual_objects/index.html.erb
<% @title = 'Intellectual Objects' %>

<div id="sidebar" class="col-md-3 col-sm-4">
  <div class="facets sidenav">
    <h3> Limit your search </h3>
    <%= render 'shared/filters/access_filter' %>
    <%= render 'shared/filters/format_filter' %>
    <%= render 'shared/filters/institution_filter' %>
    <%= render 'shared/filters/state_filter' %>
  </div>
</div>

<div id="content" class="col-md-9 col-sm-8">
  <h2 class="top-content-title long_names">Intellectual Objects for <%= @institution.name %></h2>
  <%= render 'shared/search_breadcrumb' %>
  <%= render 'shared/sort_and_per_page' %>
  <hr>
  <%- if @paged_results.empty? %>
      <%= render 'shared/zero_results' %>
  <%- else %>
      <%= render 'shared/search_results' %>
  <%- end %>
  <%= render 'shared/compact_pagination' %>
</div>

app/views/intellectual_objects/show.html.erb
<% @title = "Object #{@intellectual_object.identifier}" %>

<div id="content" class="col-md-9 show-document">
  <ol class="breadcrumb">
    <li><%= link_to @institution.name, institution_path(@institution) %></li>
    <li class="active"><%= @intellectual_object.title %></li>
  </ol>

  <div class="page-header">
    <h1 class="long_names"><%= @intellectual_object.title %></h1>
  </div>

  <div class="object_info">
    <dl class="dl-horizontal dl-invert">
      <dt>Institution</dt>
      <dd><%= link_to @institution.name, institution_path(@institution) %></dd>
      <dt>Access</dt>
      <dd><%= @intellectual_object.access.capitalize %></dd>
      <dt>Identifier</dt>
      <dd><%= @intellectual_object.identifier %></dd>
      <dt>Bag Group Identifier</dt>
      <% if @intellectual_object.bag_group_identifier.blank? %>
          <dd>-------</dd>
      <% else %>
          <dd><%= link_to @intellectual_object.bag_group_identifier, search_path(object_type: 'Intellectual Objects', search_field: 'Bag Group Identifier', q: @intellectual_object.bag_group_identifier) %></dd>
      <% end %>
      <dt>Source Organization</dt>
      <% if @intellectual_object.source_organization.blank? %>
          <dd>-------</dd>
      <% else %>
          <dd><%= link_to @intellectual_object.source_organization, search_path(object_type: 'Intellectual Objects', search_field: 'Source Organization', q: @intellectual_object.source_organization) %></dd>
      <% end %>
      <dt>Internal Sender Identifier</dt>
      <% if @intellectual_object.internal_sender_identifier.blank? %>
          <dd>-------</dd>
      <% else %>
          <dd><%= link_to @intellectual_object.internal_sender_identifier, search_path(object_type: 'Intellectual Objects', search_field: 'Internal Sender Identifier', q: @intellectual_object.internal_sender_identifier) %></dd>
      <% end %>
      <dt>Internal Sender Description</dt>
      <% if @intellectual_object.internal_sender_description.blank? %>
          <dd>-------</dd>
      <% else %>
          <dd><%= @intellectual_object.internal_sender_description%></dd>
      <% end %>
      <dt>Bag Name</dt>
      <dd><%= @intellectual_object.bag_name %></dd>
      <dt> Created </dt>
      <dd> <%= pretty_date(@intellectual_object.created_at) %> </dd>
      <dt> Last Modified </dt>
      <dd> <%= pretty_date(@intellectual_object.updated_at) %> </dd>
      <dt>Description</dt>
      <dd><%= @intellectual_object.description %></dd>
      <dt>Alternate Identifier</dt>
      <dd><%= @intellectual_object.alt_identifier %></dd>
      <dt>Storage Type</dt>
      <dd><%= @intellectual_object.storage_option %></dd>
      <% if @intellectual_object.state == 'D' %>
          <dt><i><b>State</b></i></dt>
          <dd><i>This object has been deleted.</i></dd>
      <% end %>
    </dl>
  </div>

  <div class="panel">
    <%= link_to intellectual_object_files_path(@intellectual_object), {class: 'btn doc-action-btn btn-normal'} do %>
        <i class="glyphicon glyphicon-list-alt"></i> View Preserved Files
    <% end %>
    <%= link_to intellectual_object_events_path(@intellectual_object), {class: 'btn doc-action-btn btn-normal'} do %>
        <i class="glyphicon glyphicon-eye-open"></i> View Events
    <% end %>
    <%= link_to object_report_path(@intellectual_object), {class: 'btn doc-action-btn, btn-normal'} do %>
        <i class="glyphicon glyphicon-list"></i> View Object Report
    <% end %>
    <% unless @intellectual_object.state == 'D' || @intellectual_object.all_files_deleted?  %>
        <% if current_user.admin? || (current_user.institutional_admin? && current_user.institution_id == @intellectual_object.institution_id) %>
            <%= link_to intellectual_object_restore_path(@intellectual_object.identifier), {class: 'btn doc-action-btn btn-normal'} do %>
                <i class="glyphicon glyphicon-download"></i> Restore Object
            <% end %>
            <%= destroy_link(@intellectual_object) %>
        <% end %>
    <% end %>
  </div>

</div>